#!/usr/bin/env bash
set -euo pipefail

# Affiliate Magnet Website - one script setup
# Usage examples:
#   bash create-affiliate-website.sh
#   SITE_NAME="GearWise" NICHE="home office gear" PROJECT_NAME="gearwise-affiliate" SITE_URL="https://gearwise.com" bash create-affiliate-website.sh
# Optional deployment:
#   DEPLOY_VERCEL=true CREATE_GITHUB=true GITHUB_REPO="gearwise-affiliate" bash create-affiliate-website.sh

PROJECT_NAME="${PROJECT_NAME:-affiliate-magnet-site}"
SITE_NAME="${SITE_NAME:-TrustPick}"
NICHE="${NICHE:-everyday products}"
SITE_URL="${SITE_URL:-https://example.com}"
TAGLINE="${TAGLINE:-Simple product picks you can actually understand.}"
DESCRIPTION="${DESCRIPTION:-A clean, honest affiliate website that helps people choose useful products without hype.}"
EMAIL="${EMAIL:-hello@example.com}"
GITHUB_REPO="${GITHUB_REPO:-$PROJECT_NAME}"
CREATE_GITHUB="${CREATE_GITHUB:-false}"
DEPLOY_VERCEL="${DEPLOY_VERCEL:-false}"
SKIP_INSTALL="${SKIP_INSTALL:-false}"
SKIP_BUILD="${SKIP_BUILD:-false}"
SKIP_GIT="${SKIP_GIT:-false}"

say() { printf '\n\033[1;36m%s\033[0m\n' "$1"; }
warn() { printf '\n\033[1;33m%s\033[0m\n' "$1"; }

if ! command -v node >/dev/null 2>&1; then
  echo "Node.js is required. Install Node.js 20+ first, then run this script again."
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "npm is required. It usually comes with Node.js."
  exit 1
fi

say "Creating $SITE_NAME affiliate website in ./$PROJECT_NAME"
mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

mkdir -p app/products/[slug] app/best/[category] app/disclosure app/about app/search components data lib public

cat > package.json <<'EOF'
{
  "name": "affiliate-magnet-site",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^16.0.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@types/node": "^24.0.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "typescript": "^5.9.0"
  }
}
EOF

cat > tsconfig.json <<'EOF'
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "baseUrl": ".",
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF

cat > next-env.d.ts <<'EOF'
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is automatically generated by Next.js. Do not edit it manually.
EOF

cat > .gitignore <<'EOF'
node_modules
.next
out
.env*.local
.vercel
.DS_Store
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
EOF

cat > .env.example <<'EOF'
# Copy to .env.local only if you need runtime environment variables later.
# This starter site does not require secrets.
NEXT_PUBLIC_SITE_URL=https://your-domain.com
EOF

cat > vercel.json <<'EOF'
{
  "headers": [
    {
      "source": "/(.*)",
      "headers": [
        { "key": "X-Frame-Options", "value": "DENY" },
        { "key": "X-Content-Type-Options", "value": "nosniff" },
        { "key": "Referrer-Policy", "value": "strict-origin-when-cross-origin" }
      ]
    }
  ]
}
EOF

# Create site config safely with Node so quotes/spaces are handled correctly.
SITE_NAME="$SITE_NAME" NICHE="$NICHE" SITE_URL="$SITE_URL" TAGLINE="$TAGLINE" DESCRIPTION="$DESCRIPTION" EMAIL="$EMAIL" node <<'NODE' > data/site.ts
const cfg = {
  name: process.env.SITE_NAME,
  niche: process.env.NICHE,
  siteUrl: process.env.SITE_URL,
  tagline: process.env.TAGLINE,
  description: process.env.DESCRIPTION,
  email: process.env.EMAIL,
  affiliateDisclosure:
    "Some links on this site are affiliate links. If you buy through them, we may earn a small commission at no extra cost to you. We keep recommendations practical, simple, and honest."
};
console.log(`export const siteConfig = ${JSON.stringify(cfg, null, 2)} as const;`);
NODE

cat > data/products.ts <<'EOF'
export type Product = {
  slug: string;
  name: string;
  brand: string;
  category: string;
  categorySlug: string;
  emoji: string;
  headline: string;
  summary: string;
  bestFor: string;
  priceNote: string;
  affiliateUrl: string;
  keyBenefits: string[];
  watchOut: string[];
  whyItEarnsTrust: string;
  buyingTip: string;
  price?: string;
  currency?: string;
  availability?: "https://schema.org/InStock" | "https://schema.org/OutOfStock" | "https://schema.org/PreOrder";
};

export const products: Product[] = [
  {
    slug: "quietdesk-led-lamp",
    name: "QuietDesk LED Lamp",
    brand: "QuietDesk",
    category: "Home Office",
    categorySlug: "home-office",
    emoji: "💡",
    headline: "Soft desk light that makes late work feel easier.",
    summary:
      "A clean desk lamp for people who want calm lighting, less eye strain, and a workspace that still feels warm.",
    bestFor: "Small desks, home offices, and night reading",
    priceNote: "Usually budget-friendly",
    affiliateUrl: "https://example.com/quietdesk-led-lamp?ref=YOUR_AFFILIATE_ID",
    keyBenefits: [
      "Adjustable brightness for different times of day",
      "Small footprint, so it does not crowd your desk",
      "Simple controls without a complicated app"
    ],
    watchOut: [
      "Not ideal if you need a large floor lamp",
      "Check the plug type before buying"
    ],
    whyItEarnsTrust:
      "It solves a real daily problem without asking people to change their whole setup.",
    buyingTip:
      "Choose it if you want a practical lamp first, not a gadget full of features you may never use."
  },
  {
    slug: "carrylite-travel-organizer",
    name: "CarryLite Travel Organizer",
    brand: "CarryLite",
    category: "Travel",
    categorySlug: "travel",
    emoji: "🎒",
    headline: "Keep chargers, cables, and small gear in one calm place.",
    summary:
      "A compact organizer that helps people pack faster and avoid digging through a bag at the airport, hotel, or office.",
    bestFor: "Frequent travelers, commuters, and remote workers",
    priceNote: "Mid-range",
    affiliateUrl: "https://example.com/carrylite-travel-organizer?ref=YOUR_AFFILIATE_ID",
    keyBenefits: [
      "Separate pockets for cables, adapters, and small accessories",
      "Slim enough for backpacks and carry-ons",
      "Makes packing easier to repeat every time"
    ],
    watchOut: [
      "May feel small if you carry many bulky chargers",
      "Soft-sided design protects from scratches, not heavy impact"
    ],
    whyItEarnsTrust:
      "The value is easy to understand: less mess, less stress, fewer lost accessories.",
    buyingTip:
      "Pick this if your tech accessories usually end up loose at the bottom of your bag."
  },
  {
    slug: "flowbottle-daily-tumbler",
    name: "FlowBottle Daily Tumbler",
    brand: "FlowBottle",
    category: "Everyday Carry",
    categorySlug: "everyday-carry",
    emoji: "🥤",
    headline: "A simple tumbler you will actually remember to use.",
    summary:
      "A daily bottle for people who want cold drinks, fewer disposable cups, and a design that does not look too sporty.",
    bestFor: "Work desks, gym bags, school, and commuting",
    priceNote: "Budget to mid-range",
    affiliateUrl: "https://example.com/flowbottle-daily-tumbler?ref=YOUR_AFFILIATE_ID",
    keyBenefits: [
      "Easy to carry and clean",
      "Keeps drinks cold for normal daily use",
      "Neutral style that fits work or travel"
    ],
    watchOut: [
      "Check if it fits your car cup holder",
      "Not every lid style is fully leakproof"
    ],
    whyItEarnsTrust:
      "It is not a miracle product. It is just a useful daily item that can save money and reduce waste.",
    buyingTip:
      "Choose the size based on where you use it most: smaller for commuting, larger for long days out."
  },
  {
    slug: "soundnest-sleep-earbuds",
    name: "SoundNest Sleep Earbuds",
    brand: "SoundNest",
    category: "Wellness",
    categorySlug: "wellness",
    emoji: "🎧",
    headline: "Tiny earbuds for people who need quieter nights.",
    summary:
      "A low-profile audio option for relaxing, blocking distractions, or listening to calming sounds before sleep.",
    bestFor: "Light sleepers, shared rooms, and evening routines",
    priceNote: "Premium compared with basic earbuds",
    affiliateUrl: "https://example.com/soundnest-sleep-earbuds?ref=YOUR_AFFILIATE_ID",
    keyBenefits: [
      "Low-profile shape for side sleepers",
      "Good for podcasts, white noise, or calm playlists",
      "Portable case for travel"
    ],
    watchOut: [
      "Battery life matters more than loud volume here",
      "Fit can vary from person to person"
    ],
    whyItEarnsTrust:
      "Sleep products can be overhyped, so we focus on fit, comfort, and everyday usefulness instead of big promises.",
    buyingTip:
      "Buy only if the return policy is clear, because ear comfort is personal."
  },
  {
    slug: "focuspad-meeting-notebook",
    name: "FocusPad Meeting Notebook",
    brand: "FocusPad",
    category: "Productivity",
    categorySlug: "productivity",
    emoji: "📓",
    headline: "A notebook that turns messy meetings into clear next steps.",
    summary:
      "A simple paper system for capturing decisions, action items, and follow-ups without building a complicated app workflow.",
    bestFor: "Managers, freelancers, students, and consultants",
    priceNote: "Budget-friendly",
    affiliateUrl: "https://example.com/focuspad-meeting-notebook?ref=YOUR_AFFILIATE_ID",
    keyBenefits: [
      "Clear sections for notes, tasks, and decisions",
      "No battery, login, or sync issues",
      "Helps people leave meetings with next actions"
    ],
    watchOut: [
      "Not for people who want everything digital",
      "Paper size matters if you carry a small bag"
    ],
    whyItEarnsTrust:
      "It is simple, cheap, and easy to judge after one week of use.",
    buyingTip:
      "Great if you often finish calls with notes everywhere but no clear action list."
  },
  {
    slug: "cleanslate-cable-kit",
    name: "CleanSlate Cable Kit",
    brand: "CleanSlate",
    category: "Home Office",
    categorySlug: "home-office",
    emoji: "🔌",
    headline: "Make your desk look calmer in under an hour.",
    summary:
      "A basic cable management kit for people who want a cleaner desk without buying a new desk or drilling holes.",
    bestFor: "Desk setups, TV stands, and small apartments",
    priceNote: "Budget-friendly",
    affiliateUrl: "https://example.com/cleanslate-cable-kit?ref=YOUR_AFFILIATE_ID",
    keyBenefits: [
      "Reusable ties and clips for quick cleanup",
      "Works with most desks and power strips",
      "Instant visual upgrade for photos and video calls"
    ],
    watchOut: [
      "Adhesive clips may not stick well on dusty surfaces",
      "Plan your cable route before attaching anything"
    ],
    whyItEarnsTrust:
      "It is a low-cost fix with visible results. No big claims needed.",
    buyingTip:
      "Clean the surface first and leave extra slack for cables you unplug often."
  }
];

export const categories = Array.from(
  new Map(products.map((p) => [p.categorySlug, { slug: p.categorySlug, name: p.category }])).values()
);

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getProductsByCategory(categorySlug: string) {
  return products.filter((product) => product.categorySlug === categorySlug);
}

export function getCategoryName(categorySlug: string) {
  return categories.find((category) => category.slug === categorySlug)?.name ?? "Product Picks";
}
EOF

cat > lib/seo.ts <<'EOF'
import { siteConfig } from "@/data/site";
import { products } from "@/data/products";

export function absoluteUrl(path = "") {
  const base = siteConfig.siteUrl.replace(/\/$/, "");
  const normalizedPath = path.startsWith("/") ? path : `/${path}`;
  return `${base}${normalizedPath}`;
}

export function websiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: siteConfig.name,
    url: absoluteUrl(),
    description: siteConfig.description,
    potentialAction: {
      "@type": "SearchAction",
      target: `${absoluteUrl("/search")}?q={search_term_string}`,
      "query-input": "required name=search_term_string"
    }
  };
}

export function organizationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: siteConfig.name,
    url: absoluteUrl(),
    email: siteConfig.email
  };
}

export function itemListJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: `${siteConfig.name} recommended products`,
    itemListElement: products.map((product, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: product.name,
      url: absoluteUrl(`/products/${product.slug}`)
    }))
  };
}

export function productJsonLd(product: (typeof products)[number]) {
  const json: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Product",
    name: product.name,
    brand: { "@type": "Brand", name: product.brand },
    category: product.category,
    description: product.summary,
    url: absoluteUrl(`/products/${product.slug}`)
  };

  if (product.price && product.currency && product.availability) {
    json.offers = {
      "@type": "Offer",
      price: product.price,
      priceCurrency: product.currency,
      availability: product.availability,
      url: product.affiliateUrl
    };
  }

  return json;
}

export function faqJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "How do we choose products?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "We look for products that solve common daily problems, are easy to understand, and have clear trade-offs."
        }
      },
      {
        "@type": "Question",
        name: "Do affiliate links change the price?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "No. If you buy through an affiliate link, we may earn a commission at no extra cost to you."
        }
      },
      {
        "@type": "Question",
        name: "Why do we mention watch-outs?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "A product is only useful when it fits the right person. Watch-outs help readers avoid buying the wrong item."
        }
      }
    ]
  };
}
EOF

cat > components/JsonLd.tsx <<'EOF'
type JsonLdProps = {
  data: Record<string, unknown>;
};

export function JsonLd({ data }: JsonLdProps) {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
EOF

cat > components/AffiliateButton.tsx <<'EOF'
type AffiliateButtonProps = {
  href: string;
  label?: string;
  compact?: boolean;
};

export function AffiliateButton({ href, label = "Check current deal", compact = false }: AffiliateButtonProps) {
  return (
    <a
      className={compact ? "btn btn-small" : "btn"}
      href={href}
      target="_blank"
      rel="sponsored noopener noreferrer"
    >
      {label}
      <span aria-hidden="true"> →</span>
    </a>
  );
}
EOF

cat > components/Header.tsx <<'EOF'
import Link from "next/link";
import { categories } from "@/data/products";
import { siteConfig } from "@/data/site";

export function Header() {
  return (
    <header className="site-header">
      <Link href="/" className="brand" aria-label={`${siteConfig.name} home`}>
        <span className="brand-mark">✦</span>
        <span>{siteConfig.name}</span>
      </Link>
      <nav className="nav" aria-label="Main navigation">
        {categories.slice(0, 4).map((category) => (
          <Link key={category.slug} href={`/best/${category.slug}`}>
            {category.name}
          </Link>
        ))}
        <Link href="/about">About</Link>
      </nav>
    </header>
  );
}
EOF

cat > components/Footer.tsx <<'EOF'
import Link from "next/link";
import { siteConfig } from "@/data/site";

export function Footer() {
  return (
    <footer className="footer">
      <div>
        <p className="footer-logo">{siteConfig.name}</p>
        <p>{siteConfig.affiliateDisclosure}</p>
      </div>
      <div className="footer-links">
        <Link href="/about">About</Link>
        <Link href="/disclosure">Affiliate disclosure</Link>
        <Link href="/search">Search</Link>
      </div>
    </footer>
  );
}
EOF

cat > components/ProductCard.tsx <<'EOF'
import Link from "next/link";
import type { Product } from "@/data/products";
import { AffiliateButton } from "@/components/AffiliateButton";

export function ProductCard({ product, priority = false }: { product: Product; priority?: boolean }) {
  return (
    <article className={priority ? "product-card product-card-featured" : "product-card"}>
      <div className="product-visual" aria-hidden="true">
        <span>{product.emoji}</span>
      </div>
      <div className="product-content">
        <div className="eyebrow">{product.category}</div>
        <h3>
          <Link href={`/products/${product.slug}`}>{product.name}</Link>
        </h3>
        <p>{product.summary}</p>
        <div className="mini-grid">
          <span><strong>Best for:</strong> {product.bestFor}</span>
          <span><strong>Price:</strong> {product.priceNote}</span>
        </div>
        <div className="card-actions">
          <Link href={`/products/${product.slug}`} className="text-link">Read quick review</Link>
          <AffiliateButton href={product.affiliateUrl} compact />
        </div>
      </div>
    </article>
  );
}
EOF

cat > components/TrustBar.tsx <<'EOF'
export function TrustBar() {
  const items = [
    ["Clear picks", "No confusing jargon or fake urgency."],
    ["Real trade-offs", "Every product includes watch-outs."],
    ["Simple English", "Easy to scan before buying."],
    ["Affiliate clear", "Links are disclosed and marked." ]
  ];

  return (
    <section className="trust-bar" aria-label="Why readers can trust this site">
      {items.map(([title, text]) => (
        <div key={title}>
          <strong>{title}</strong>
          <span>{text}</span>
        </div>
      ))}
    </section>
  );
}
EOF

cat > app/layout.tsx <<'EOF'
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { siteConfig } from "@/data/site";
import { absoluteUrl, organizationJsonLd, websiteJsonLd } from "@/lib/seo";
import { JsonLd } from "@/components/JsonLd";

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.siteUrl),
  title: {
    default: `${siteConfig.name} — ${siteConfig.tagline}`,
    template: `%s | ${siteConfig.name}`
  },
  description: siteConfig.description,
  alternates: {
    canonical: absoluteUrl()
  },
  openGraph: {
    type: "website",
    url: absoluteUrl(),
    title: `${siteConfig.name} — ${siteConfig.tagline}`,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: [
      {
        url: absoluteUrl("/og.svg"),
        width: 1200,
        height: 630,
        alt: `${siteConfig.name} product picks`
      }
    ]
  },
  twitter: {
    card: "summary_large_image",
    title: `${siteConfig.name} — ${siteConfig.tagline}`,
    description: siteConfig.description,
    images: [absoluteUrl("/og.svg")]
  }
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <JsonLd data={websiteJsonLd()} />
        <JsonLd data={organizationJsonLd()} />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
EOF

cat > app/page.tsx <<'EOF'
import Link from "next/link";
import { ProductCard } from "@/components/ProductCard";
import { TrustBar } from "@/components/TrustBar";
import { JsonLd } from "@/components/JsonLd";
import { categories, products } from "@/data/products";
import { siteConfig } from "@/data/site";
import { faqJsonLd, itemListJsonLd } from "@/lib/seo";

export default function HomePage() {
  const featured = products.slice(0, 3);
  const moreProducts = products.slice(3);

  return (
    <>
      <JsonLd data={itemListJsonLd()} />
      <JsonLd data={faqJsonLd()} />
      <section className="hero">
        <div className="hero-copy">
          <p className="pill">Independent picks for {siteConfig.niche}</p>
          <h1>Useful products, explained in simple English.</h1>
          <p className="hero-subtitle">
            We help you choose products that solve real problems. No hype, no confusing specs, and no pretending every item is perfect.
          </p>
          <div className="hero-actions">
            <a href="#best-picks" className="btn">See best picks</a>
            <Link href="/disclosure" className="secondary-btn">How we earn</Link>
          </div>
        </div>
        <div className="hero-panel" aria-label="Featured buying promise">
          <div className="score-card">
            <span className="score">01</span>
            <strong>Start with the problem</strong>
            <p>We explain who each product is for before asking you to click.</p>
          </div>
          <div className="score-card floating">
            <span className="score">02</span>
            <strong>Show the trade-off</strong>
            <p>Good products still have limits. We make them easy to see.</p>
          </div>
          <div className="glow-orb" />
        </div>
      </section>

      <TrustBar />

      <section id="best-picks" className="section">
        <div className="section-heading">
          <p className="eyebrow">Best starting points</p>
          <h2>Product picks people can understand fast.</h2>
          <p>
            Each recommendation uses plain language, clear benefits, and honest watch-outs so readers feel informed, not pushed.
          </p>
        </div>
        <div className="product-grid featured-grid">
          {featured.map((product, index) => (
            <ProductCard key={product.slug} product={product} priority={index === 0} />
          ))}
        </div>
      </section>

      <section className="section split-section">
        <div>
          <p className="eyebrow">Browse by need</p>
          <h2>Find the right product category.</h2>
        </div>
        <div className="category-grid">
          {categories.map((category) => (
            <Link href={`/best/${category.slug}`} key={category.slug} className="category-card">
              <span>{category.name}</span>
              <small>View picks →</small>
            </Link>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading compact-heading">
          <p className="eyebrow">More helpful picks</p>
          <h2>Small upgrades that make daily life easier.</h2>
        </div>
        <div className="product-grid">
          {moreProducts.map((product) => (
            <ProductCard key={product.slug} product={product} />
          ))}
        </div>
      </section>

      <section className="section comparison-section">
        <div className="section-heading compact-heading">
          <p className="eyebrow">Quick comparison</p>
          <h2>Choose based on the job, not the loudest ad.</h2>
        </div>
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Product</th>
                <th>Best for</th>
                <th>Price feel</th>
                <th>Main watch-out</th>
              </tr>
            </thead>
            <tbody>
              {products.slice(0, 5).map((product) => (
                <tr key={product.slug}>
                  <td><Link href={`/products/${product.slug}`}>{product.name}</Link></td>
                  <td>{product.bestFor}</td>
                  <td>{product.priceNote}</td>
                  <td>{product.watchOut[0]}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="section faq-section">
        <div className="section-heading compact-heading">
          <p className="eyebrow">Reader-first FAQ</p>
          <h2>Simple answers before people buy.</h2>
        </div>
        <div className="faq-grid">
          <article>
            <h3>How do we choose products?</h3>
            <p>We look for products that solve common daily problems, are easy to explain, and have trade-offs worth knowing.</p>
          </article>
          <article>
            <h3>Do affiliate links change the price?</h3>
            <p>No. We may earn a commission if someone buys through a link, but it should not add extra cost to the reader.</p>
          </article>
          <article>
            <h3>Why include watch-outs?</h3>
            <p>Trust grows when readers see both sides. A product is only a good buy when it fits the right person.</p>
          </article>
        </div>
      </section>
    </>
  );
}
EOF

cat > app/products/[slug]/page.tsx <<'EOF'
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AffiliateButton } from "@/components/AffiliateButton";
import { JsonLd } from "@/components/JsonLd";
import { getProduct, products } from "@/data/products";
import { siteConfig } from "@/data/site";
import { absoluteUrl, productJsonLd } from "@/lib/seo";

type RouteProps = {
  params: Promise<{ slug: string }> | { slug: string };
};

async function readParams(params: RouteProps["params"]) {
  return await params;
}

export function generateStaticParams() {
  return products.map((product) => ({ slug: product.slug }));
}

export async function generateMetadata({ params }: RouteProps): Promise<Metadata> {
  const { slug } = await readParams(params);
  const product = getProduct(slug);

  if (!product) {
    return { title: "Product not found" };
  }

  return {
    title: `${product.name} review`,
    description: product.summary,
    alternates: { canonical: absoluteUrl(`/products/${product.slug}`) },
    openGraph: {
      title: `${product.name} review`,
      description: product.summary,
      url: absoluteUrl(`/products/${product.slug}`),
      type: "article"
    }
  };
}

export default async function ProductPage({ params }: RouteProps) {
  const { slug } = await readParams(params);
  const product = getProduct(slug);

  if (!product) {
    notFound();
  }

  return (
    <>
      <JsonLd data={productJsonLd(product)} />
      <article className="product-page">
        <nav className="breadcrumb" aria-label="Breadcrumb">
          <Link href="/">Home</Link> <span>/</span> <Link href={`/best/${product.categorySlug}`}>{product.category}</Link> <span>/</span> <span>{product.name}</span>
        </nav>

        <section className="product-hero">
          <div className="product-hero-visual" aria-hidden="true">{product.emoji}</div>
          <div>
            <p className="pill">{product.category}</p>
            <h1>{product.name}</h1>
            <p className="hero-subtitle">{product.headline}</p>
            <p>{product.summary}</p>
            <div className="hero-actions">
              <AffiliateButton href={product.affiliateUrl} label="Check current price" />
              <Link href={`/best/${product.categorySlug}`} className="secondary-btn">Compare category</Link>
            </div>
            <p className="small-note">{siteConfig.affiliateDisclosure}</p>
          </div>
        </section>

        <section className="review-grid">
          <div className="review-card">
            <h2>Why it is worth considering</h2>
            <ul>
              {product.keyBenefits.map((benefit) => <li key={benefit}>{benefit}</li>)}
            </ul>
          </div>
          <div className="review-card muted-card">
            <h2>Watch-outs</h2>
            <ul>
              {product.watchOut.map((item) => <li key={item}>{item}</li>)}
            </ul>
          </div>
        </section>

        <section className="section text-section">
          <h2>Who should buy this?</h2>
          <p>{product.bestFor}. The strongest reason to consider it: {product.whyItEarnsTrust}</p>

          <h2>Simple buying tip</h2>
          <p>{product.buyingTip}</p>

          <h2>Bottom line</h2>
          <p>
            {product.name} is a good fit if you want a practical product that solves a clear problem. It may not be the most advanced option, but that is part of the appeal: it is easy to understand and easy to use.
          </p>
        </section>
      </article>
    </>
  );
}
EOF

cat > app/best/[category]/page.tsx <<'EOF'
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProductCard } from "@/components/ProductCard";
import { categories, getCategoryName, getProductsByCategory } from "@/data/products";
import { absoluteUrl } from "@/lib/seo";

type RouteProps = {
  params: Promise<{ category: string }> | { category: string };
};

async function readParams(params: RouteProps["params"]) {
  return await params;
}

export function generateStaticParams() {
  return categories.map((category) => ({ category: category.slug }));
}

export async function generateMetadata({ params }: RouteProps): Promise<Metadata> {
  const { category } = await readParams(params);
  const name = getCategoryName(category);
  const picks = getProductsByCategory(category);

  if (!picks.length) return { title: "Category not found" };

  return {
    title: `Best ${name} picks`,
    description: `Simple, honest ${name.toLowerCase()} product picks with clear benefits and watch-outs.`,
    alternates: { canonical: absoluteUrl(`/best/${category}`) }
  };
}

export default async function CategoryPage({ params }: RouteProps) {
  const { category } = await readParams(params);
  const picks = getProductsByCategory(category);
  const name = getCategoryName(category);

  if (!picks.length) {
    notFound();
  }

  return (
    <section className="section category-page">
      <nav className="breadcrumb" aria-label="Breadcrumb">
        <Link href="/">Home</Link> <span>/</span> <span>{name}</span>
      </nav>
      <div className="section-heading">
        <p className="eyebrow">Best {name}</p>
        <h1>Simple {name.toLowerCase()} picks with honest trade-offs.</h1>
        <p>
          These picks are written for real buyers who want quick clarity, not a wall of confusing specifications.
        </p>
      </div>
      <div className="product-grid">
        {picks.map((product) => <ProductCard key={product.slug} product={product} />)}
      </div>
    </section>
  );
}
EOF

cat > app/disclosure/page.tsx <<'EOF'
import type { Metadata } from "next";
import { siteConfig } from "@/data/site";
import { absoluteUrl } from "@/lib/seo";

export const metadata: Metadata = {
  title: "Affiliate disclosure",
  description: "How this website uses affiliate links and keeps recommendations transparent.",
  alternates: { canonical: absoluteUrl("/disclosure") }
};

export default function DisclosurePage() {
  return (
    <section className="section text-section narrow">
      <p className="eyebrow">Transparency</p>
      <h1>Affiliate disclosure</h1>
      <p>{siteConfig.affiliateDisclosure}</p>
      <p>
        Our goal is to help readers make better buying decisions. We try to explain the use case, benefits, and watch-outs in plain English. Affiliate income helps keep the site running, but it should not decide whether a product is useful for a reader.
      </p>
      <p>
        Before buying, readers should always check the latest price, warranty, return policy, shipping details, and product fit on the seller website.
      </p>
    </section>
  );
}
EOF

cat > app/about/page.tsx <<'EOF'
import type { Metadata } from "next";
import { siteConfig } from "@/data/site";
import { absoluteUrl } from "@/lib/seo";

export const metadata: Metadata = {
  title: "About",
  description: `About ${siteConfig.name} and how we choose product recommendations.`,
  alternates: { canonical: absoluteUrl("/about") }
};

export default function AboutPage() {
  return (
    <section className="section text-section narrow">
      <p className="eyebrow">About {siteConfig.name}</p>
      <h1>We make product research feel simple.</h1>
      <p>
        {siteConfig.name} is built for people who want to buy useful products without reading ten tabs, twenty reviews, and a page full of specs.
      </p>
      <p>
        We focus on clear use cases, practical benefits, and honest trade-offs. A recommendation is only good when the reader understands who it is for and who should skip it.
      </p>
      <div className="review-grid">
        <div className="review-card">
          <h2>Our content rules</h2>
          <ul>
            <li>Use simple English.</li>
            <li>Explain the problem first.</li>
            <li>Mention watch-outs clearly.</li>
            <li>Keep affiliate disclosure visible.</li>
          </ul>
        </div>
        <div className="review-card muted-card">
          <h2>What to edit next</h2>
          <ul>
            <li>Add your real niche and brand voice.</li>
            <li>Replace sample products with real products.</li>
            <li>Add original photos or hands-on notes.</li>
            <li>Publish supporting guides for long-tail SEO.</li>
          </ul>
        </div>
      </div>
    </section>
  );
}
EOF

cat > app/search/page.tsx <<'EOF'
import Link from "next/link";
import type { Metadata } from "next";
import { products } from "@/data/products";
import { absoluteUrl } from "@/lib/seo";

export const metadata: Metadata = {
  title: "Search product picks",
  description: "Search simple product recommendations by name, category, or use case.",
  alternates: { canonical: absoluteUrl("/search") }
};

type SearchProps = {
  searchParams: Promise<{ q?: string }> | { q?: string };
};

export default async function SearchPage({ searchParams }: SearchProps) {
  const params = await searchParams;
  const q = (params.q ?? "").trim().toLowerCase();
  const results = q
    ? products.filter((product) =>
        [product.name, product.category, product.summary, product.bestFor].join(" ").toLowerCase().includes(q)
      )
    : products;

  return (
    <section className="section text-section narrow">
      <p className="eyebrow">Search</p>
      <h1>Find a product pick</h1>
      <form action="/search" className="search-form">
        <input name="q" defaultValue={q} placeholder="Try: desk, travel, sleep..." aria-label="Search product picks" />
        <button className="btn" type="submit">Search</button>
      </form>
      <div className="search-results">
        {results.map((product) => (
          <Link href={`/products/${product.slug}`} key={product.slug} className="search-result-card">
            <strong>{product.name}</strong>
            <span>{product.summary}</span>
          </Link>
        ))}
        {!results.length && <p>No product matched that search. Try a broader word.</p>}
      </div>
    </section>
  );
}
EOF

cat > app/not-found.tsx <<'EOF'
import Link from "next/link";

export default function NotFound() {
  return (
    <section className="section text-section narrow">
      <p className="eyebrow">404</p>
      <h1>Page not found</h1>
      <p>The page may have moved, or the product no longer exists.</p>
      <Link href="/" className="btn">Back to home</Link>
    </section>
  );
}
EOF

cat > app/robots.ts <<'EOF'
import type { MetadataRoute } from "next";
import { siteConfig } from "@/data/site";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/"
    },
    sitemap: `${siteConfig.siteUrl.replace(/\/$/, "")}/sitemap.xml`
  };
}
EOF

cat > app/sitemap.ts <<'EOF'
import type { MetadataRoute } from "next";
import { categories, products } from "@/data/products";
import { siteConfig } from "@/data/site";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = siteConfig.siteUrl.replace(/\/$/, "");
  const now = new Date();

  const staticRoutes = ["", "/about", "/disclosure", "/search"].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: route === "" ? 1 : 0.7
  }));

  const productRoutes = products.map((product) => ({
    url: `${baseUrl}/products/${product.slug}`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: 0.85
  }));

  const categoryRoutes = categories.map((category) => ({
    url: `${baseUrl}/best/${category.slug}`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: 0.8
  }));

  return [...staticRoutes, ...categoryRoutes, ...productRoutes];
}
EOF

cat > app/globals.css <<'EOF'
:root {
  --bg: #09111f;
  --bg-soft: #0e1a2c;
  --panel: rgba(255, 255, 255, 0.08);
  --panel-strong: rgba(255, 255, 255, 0.14);
  --text: #f8fafc;
  --muted: #aebcd0;
  --line: rgba(255, 255, 255, 0.14);
  --brand: #8cf7d2;
  --brand-2: #95b8ff;
  --accent: #fff2a8;
  --shadow: 0 24px 80px rgba(0, 0, 0, 0.32);
}

* { box-sizing: border-box; }

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  color: var(--text);
  background:
    radial-gradient(circle at top left, rgba(140, 247, 210, 0.22), transparent 34rem),
    radial-gradient(circle at 85% 10%, rgba(149, 184, 255, 0.22), transparent 32rem),
    linear-gradient(135deg, #07101d 0%, #0b1424 45%, #111827 100%);
  min-height: 100vh;
}

a { color: inherit; text-decoration: none; }

p { color: var(--muted); line-height: 1.75; }

strong { color: var(--text); }

.site-header {
  position: sticky;
  top: 0;
  z-index: 50;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1.5rem;
  padding: 1rem clamp(1rem, 4vw, 4rem);
  background: rgba(7, 16, 29, 0.72);
  backdrop-filter: blur(18px);
  border-bottom: 1px solid var(--line);
}

.brand {
  display: inline-flex;
  align-items: center;
  gap: 0.65rem;
  font-weight: 850;
  letter-spacing: -0.03em;
  font-size: 1.1rem;
}

.brand-mark {
  display: grid;
  place-items: center;
  width: 2.25rem;
  height: 2.25rem;
  border-radius: 0.85rem;
  background: linear-gradient(135deg, var(--brand), var(--brand-2));
  color: #07101d;
  box-shadow: 0 12px 35px rgba(140, 247, 210, 0.28);
}

.nav {
  display: flex;
  align-items: center;
  gap: 1rem;
  flex-wrap: wrap;
  color: var(--muted);
  font-size: 0.95rem;
}

.nav a:hover { color: var(--text); }

.hero {
  display: grid;
  grid-template-columns: minmax(0, 1.08fr) minmax(320px, 0.92fr);
  gap: clamp(2rem, 5vw, 5rem);
  padding: clamp(4rem, 10vw, 8rem) clamp(1rem, 4vw, 4rem) 3rem;
  max-width: 1240px;
  margin: 0 auto;
  align-items: center;
}

.hero-copy h1,
.section-heading h1,
.product-hero h1,
.text-section h1 {
  margin: 0;
  max-width: 14ch;
  font-size: clamp(3rem, 8vw, 6.85rem);
  line-height: 0.9;
  letter-spacing: -0.075em;
}

.section-heading h1,
.product-hero h1,
.text-section h1 {
  max-width: 13ch;
  font-size: clamp(2.7rem, 7vw, 5.5rem);
}

.hero-subtitle {
  max-width: 680px;
  font-size: clamp(1.1rem, 2vw, 1.35rem);
  color: #d8e4f4;
}

.pill,
.eyebrow {
  display: inline-flex;
  width: fit-content;
  align-items: center;
  gap: 0.4rem;
  margin: 0 0 1rem;
  padding: 0.48rem 0.75rem;
  border: 1px solid var(--line);
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.06);
  color: var(--brand);
  font-size: 0.8rem;
  font-weight: 800;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.hero-actions,
.card-actions {
  display: flex;
  gap: 0.8rem;
  flex-wrap: wrap;
  align-items: center;
  margin-top: 1.75rem;
}

.btn,
.secondary-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 999px;
  min-height: 3.1rem;
  padding: 0.9rem 1.22rem;
  font-weight: 850;
  transition: transform 180ms ease, border-color 180ms ease, background 180ms ease;
}

.btn {
  color: #06111f;
  background: linear-gradient(135deg, var(--brand), var(--accent));
  box-shadow: 0 18px 48px rgba(140, 247, 210, 0.2);
}

.btn:hover,
.secondary-btn:hover,
.product-card:hover,
.category-card:hover,
.search-result-card:hover {
  transform: translateY(-3px);
}

.secondary-btn {
  border: 1px solid var(--line);
  color: var(--text);
  background: rgba(255, 255, 255, 0.06);
}

.btn-small {
  min-height: 2.5rem;
  padding: 0.65rem 0.92rem;
  font-size: 0.9rem;
}

.hero-panel {
  position: relative;
  min-height: 480px;
  border-radius: 2.5rem;
  background:
    linear-gradient(160deg, rgba(255, 255, 255, 0.16), rgba(255, 255, 255, 0.06)),
    radial-gradient(circle at 80% 10%, rgba(255, 242, 168, 0.25), transparent 18rem);
  border: 1px solid var(--line);
  box-shadow: var(--shadow);
  overflow: hidden;
  padding: 1.25rem;
}

.score-card {
  position: relative;
  z-index: 2;
  width: min(85%, 360px);
  padding: 1.35rem;
  border-radius: 1.5rem;
  background: rgba(9, 17, 31, 0.62);
  border: 1px solid var(--line);
  box-shadow: 0 18px 60px rgba(0, 0, 0, 0.22);
}

.score-card.floating {
  margin: 8rem 0 0 auto;
}

.score {
  display: block;
  margin-bottom: 1.7rem;
  color: var(--brand);
  font-weight: 900;
  letter-spacing: -0.04em;
}

.glow-orb {
  position: absolute;
  inset: auto -7rem -7rem auto;
  width: 23rem;
  height: 23rem;
  border-radius: 999px;
  background: linear-gradient(135deg, var(--brand), var(--brand-2));
  filter: blur(12px);
  opacity: 0.45;
}

.trust-bar,
.section,
.footer {
  max-width: 1240px;
  margin: 0 auto;
  padding-inline: clamp(1rem, 4vw, 4rem);
}

.trust-bar {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1rem;
  padding-top: 1.2rem;
  padding-bottom: 4rem;
}

.trust-bar div,
.review-card,
.product-card,
.category-card,
.search-result-card,
.table-wrap,
.faq-grid article {
  border: 1px solid var(--line);
  background: var(--panel);
  border-radius: 1.4rem;
  box-shadow: 0 16px 44px rgba(0, 0, 0, 0.13);
}

.trust-bar div {
  padding: 1rem;
}

.trust-bar strong,
.trust-bar span {
  display: block;
}

.trust-bar span {
  margin-top: 0.4rem;
  color: var(--muted);
  font-size: 0.92rem;
  line-height: 1.5;
}

.section {
  padding-top: 3rem;
  padding-bottom: 3rem;
}

.section-heading {
  max-width: 800px;
  margin-bottom: 2rem;
}

.section-heading h2,
.text-section h2 {
  margin: 0;
  font-size: clamp(2rem, 4vw, 3.75rem);
  line-height: 0.95;
  letter-spacing: -0.055em;
}

.compact-heading h2 { max-width: 720px; }

.product-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1rem;
}

.featured-grid {
  grid-template-columns: 1.2fr 0.9fr 0.9fr;
}

.product-card {
  position: relative;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  transition: transform 180ms ease, background 180ms ease, border-color 180ms ease;
}

.product-card:hover,
.category-card:hover,
.search-result-card:hover {
  border-color: rgba(140, 247, 210, 0.45);
  background: var(--panel-strong);
}

.product-card-featured .product-visual {
  min-height: 230px;
}

.product-visual {
  display: grid;
  place-items: center;
  min-height: 165px;
  background:
    radial-gradient(circle at 50% 30%, rgba(255, 242, 168, 0.34), transparent 10rem),
    linear-gradient(135deg, rgba(140, 247, 210, 0.18), rgba(149, 184, 255, 0.2));
}

.product-visual span,
.product-hero-visual {
  font-size: 4rem;
  filter: drop-shadow(0 18px 35px rgba(0, 0, 0, 0.28));
}

.product-content {
  display: flex;
  flex: 1;
  flex-direction: column;
  padding: 1.25rem;
}

.product-content h3 {
  margin: 0 0 0.5rem;
  font-size: 1.35rem;
  letter-spacing: -0.035em;
}

.product-content h3 a:hover,
table a:hover,
.text-link:hover { color: var(--brand); }

.product-content p { margin-top: 0; }

.mini-grid {
  display: grid;
  gap: 0.6rem;
  margin-top: auto;
  color: var(--muted);
  font-size: 0.92rem;
}

.text-link {
  color: var(--text);
  font-weight: 800;
}

.split-section {
  display: grid;
  grid-template-columns: 0.75fr 1.25fr;
  gap: 2rem;
  align-items: start;
}

.category-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 1rem;
}

.category-card,
.search-result-card {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  padding: 1.25rem;
  transition: transform 180ms ease, border-color 180ms ease, background 180ms ease;
}

.category-card span,
.search-result-card strong {
  font-size: 1.15rem;
  font-weight: 850;
}

.category-card small,
.search-result-card span {
  color: var(--muted);
}

.comparison-section table {
  width: 100%;
  border-collapse: collapse;
  overflow: hidden;
}

.table-wrap { overflow-x: auto; }

th, td {
  padding: 1rem;
  text-align: left;
  border-bottom: 1px solid var(--line);
  vertical-align: top;
}

th {
  color: var(--brand);
  font-size: 0.78rem;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

tr:last-child td { border-bottom: 0; }

.faq-grid,
.review-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1rem;
}

.faq-grid article,
.review-card {
  padding: 1.25rem;
}

.faq-grid h3,
.review-card h2 {
  margin-top: 0;
  letter-spacing: -0.03em;
}

.product-page {
  max-width: 1120px;
  margin: 0 auto;
  padding: 2rem clamp(1rem, 4vw, 4rem) 4rem;
}

.breadcrumb {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin: 0 0 2rem;
  color: var(--muted);
  font-size: 0.92rem;
}

.breadcrumb a:hover { color: var(--brand); }

.product-hero {
  display: grid;
  grid-template-columns: 0.75fr 1.25fr;
  gap: clamp(1.5rem, 5vw, 4rem);
  align-items: center;
  padding: clamp(1rem, 3vw, 2rem);
  border: 1px solid var(--line);
  border-radius: 2rem;
  background: var(--panel);
  box-shadow: var(--shadow);
}

.product-hero-visual {
  display: grid;
  place-items: center;
  min-height: 360px;
  border-radius: 1.5rem;
  background:
    radial-gradient(circle at 50% 30%, rgba(255, 242, 168, 0.3), transparent 13rem),
    linear-gradient(135deg, rgba(140, 247, 210, 0.18), rgba(149, 184, 255, 0.2));
  font-size: 7rem;
}

.small-note {
  margin-top: 1rem;
  font-size: 0.88rem;
}

.review-grid {
  grid-template-columns: repeat(2, 1fr);
  margin-top: 1rem;
}

.review-card ul {
  margin: 0;
  padding-left: 1.2rem;
  color: var(--muted);
  line-height: 1.8;
}

.muted-card { background: rgba(255, 255, 255, 0.055); }

.text-section {
  max-width: 880px;
}

.text-section.narrow { max-width: 820px; }

.text-section h2 { margin-top: 2rem; }

.search-form {
  display: flex;
  gap: 0.8rem;
  margin: 2rem 0;
}

.search-form input {
  flex: 1;
  min-height: 3.1rem;
  padding: 0.8rem 1rem;
  border: 1px solid var(--line);
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.08);
  color: var(--text);
  outline: none;
}

.search-form input:focus { border-color: rgba(140, 247, 210, 0.58); }

.search-results {
  display: grid;
  gap: 0.8rem;
}

.search-result-card {
  flex-direction: column;
}

.footer {
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 2rem;
  padding-top: 3rem;
  padding-bottom: 3rem;
  border-top: 1px solid var(--line);
  margin-top: 3rem;
}

.footer-logo {
  margin: 0;
  font-size: 1.1rem;
  font-weight: 900;
  color: var(--text);
}

.footer-links {
  display: flex;
  flex-direction: column;
  gap: 0.7rem;
  color: var(--muted);
}

.footer-links a:hover { color: var(--brand); }

@media (max-width: 950px) {
  .hero,
  .product-hero,
  .split-section,
  .footer {
    grid-template-columns: 1fr;
  }

  .product-grid,
  .featured-grid,
  .trust-bar,
  .faq-grid {
    grid-template-columns: repeat(2, 1fr);
  }

  .hero-panel { min-height: 390px; }
}

@media (max-width: 660px) {
  .site-header {
    align-items: flex-start;
    flex-direction: column;
  }

  .nav { gap: 0.75rem; }

  .hero { padding-top: 3rem; }

  .hero-copy h1,
  .section-heading h1,
  .product-hero h1,
  .text-section h1 {
    font-size: clamp(2.55rem, 15vw, 4.2rem);
  }

  .product-grid,
  .featured-grid,
  .trust-bar,
  .faq-grid,
  .review-grid,
  .category-grid {
    grid-template-columns: 1fr;
  }

  .hero-actions,
  .search-form {
    align-items: stretch;
    flex-direction: column;
  }

  .product-hero-visual { min-height: 220px; }
}
EOF

cat > public/favicon.svg <<EOF
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120">
  <rect width="120" height="120" rx="28" fill="#09111f"/>
  <path d="M60 18l9.8 29.8H101L75.7 66.2 85.4 96 60 77.6 34.6 96l9.7-29.8L19 47.8h31.2L60 18z" fill="#8cf7d2"/>
</svg>
EOF

cat > public/og.svg <<EOF
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <defs>
    <linearGradient id="g" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0" stop-color="#09111f"/>
      <stop offset="0.55" stop-color="#0e1a2c"/>
      <stop offset="1" stop-color="#13233a"/>
    </linearGradient>
    <radialGradient id="r" cx="0.15" cy="0.2" r="0.75">
      <stop offset="0" stop-color="#8cf7d2" stop-opacity="0.45"/>
      <stop offset="1" stop-color="#8cf7d2" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="1200" height="630" fill="url(#g)"/>
  <rect width="1200" height="630" fill="url(#r)"/>
  <circle cx="980" cy="120" r="180" fill="#95b8ff" opacity="0.2"/>
  <text x="90" y="185" fill="#8cf7d2" font-family="Arial, sans-serif" font-size="36" font-weight="700">Affiliate product picks</text>
  <text x="90" y="305" fill="#ffffff" font-family="Arial, sans-serif" font-size="86" font-weight="900">${SITE_NAME}</text>
  <text x="90" y="390" fill="#d8e4f4" font-family="Arial, sans-serif" font-size="42">${TAGLINE}</text>
  <text x="90" y="500" fill="#fff2a8" font-family="Arial, sans-serif" font-size="30">Simple. Honest. Useful.</text>
</svg>
EOF

cat > README.md <<'EOF'
# Affiliate Magnet Website

A fast Next.js affiliate website built for simple English copy, clean UI, transparent affiliate disclosure, and SEO-friendly structure.

## Quick start

```bash
npm install
npm run dev
```

Open `http://localhost:3000`.

## Edit your brand

Edit:

- `data/site.ts` for site name, URL, niche, description, email, and disclosure.
- `data/products.ts` for real affiliate products and links.

Important: replace every `YOUR_AFFILIATE_ID` placeholder with your real affiliate link or tracking ID.

## Deploy to Vercel

```bash
npm run build
npx vercel --prod
```

Or push this repo to GitHub and import it from Vercel.

## SEO checklist before publishing

- Update `siteUrl` in `data/site.ts` to your real domain.
- Replace sample products with real products.
- Use original product notes when possible.
- Keep affiliate disclosure visible.
- Use `rel="sponsored"` on affiliate links.
- Submit `/sitemap.xml` in Google Search Console.
- Test structured data with Google's Rich Results Test.

## Content growth plan

Publish long-tail pages such as:

- Best desk accessories for small apartments
- Best travel organizers for digital nomads
- Best sleep earbuds for side sleepers
- Budget cable management ideas for work desks

Long-tail content usually converts better because visitors already know the problem they want to solve.
EOF

say "Files created."

if [ "$SKIP_INSTALL" != "true" ]; then
  say "Installing dependencies"
  npm install
else
  warn "Skipping npm install because SKIP_INSTALL=true"
fi

if [ "$SKIP_BUILD" != "true" ]; then
  say "Testing production build"
  npm run build
else
  warn "Skipping build because SKIP_BUILD=true"
fi

if [ "$SKIP_GIT" != "true" ]; then
  say "Creating local git commit"
  if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git init
  fi
  git add .
  git commit -m "Initial affiliate website" || warn "Git commit skipped. You may already have a clean tree or Git identity is not configured."
else
  warn "Skipping git because SKIP_GIT=true"
fi

if [ "$CREATE_GITHUB" = "true" ]; then
  if command -v gh >/dev/null 2>&1; then
    say "Creating GitHub repo: $GITHUB_REPO"
    gh repo create "$GITHUB_REPO" --private --source=. --remote=origin --push || warn "GitHub repo creation failed. Check gh auth status."
  else
    warn "GitHub CLI not found. Install gh, run 'gh auth login', then push manually."
  fi
fi

if [ "$DEPLOY_VERCEL" = "true" ]; then
  say "Deploying to Vercel"
  if ! command -v vercel >/dev/null 2>&1; then
    npm install --global vercel@latest
  fi
  vercel --prod
else
  warn "Vercel deploy not run. To deploy now: cd $PROJECT_NAME && npx vercel --prod"
fi

say "Done. Next steps: edit data/products.ts, replace affiliate links, set your real domain in data/site.ts, then deploy."
